### ISSUE TITLE
Support for quads

### ISSUE THREAD

**Issue by Rootmars** [keharriso/love-nuklear#10]
Currently, love-nuklear does not support quads. Quads are necessary for developers that package sprites into sprite atlases. Given that [textures are going to be batched automatically](https://bitbucket.org/rude/love/commits/fbcbffef2fb9e0e7b21eb07252823aaf390e1013), it is possible that more developers are going to shift to using sprite atlases (and therefore quads) in the future.

**Comment by keharriso** [comment]
You're right, quads would be a good feature to support. I'll hopefully get around to it before too long. Thanks for the issue.

**Comment by keharriso** [comment]
I think I've finally gotten around to do this. See v2.1, you can use {Image, Quad} instead of just Image.
