### ISSUE TITLE
MVC Scrollable list and I'm sold!

### ISSUE THREAD

**Issue by F483** [keharriso/love-nuklear#11]
Having a scrollable list that I can easily add remove items from is vital for me (want to make a turn based strategy game with lots of menus).

**Comment by JanWerder** [comment]
Well you can easily have a list right now with a scrollable window and a few button within. What you are asking is doable right now

**Comment by keharriso** [comment]
I'm tentatively closing this issue, but if you or anyone else wants to elaborate on what functionality you want to see, feel free to explain.
