### ISSUE TITLE
force-focus widgets

### ISSUE THREAD

**Issue by shakesoda** [keharriso/love-nuklear#14]
for the case of in game chat, it'd be useful to be force-focus text inputs, so you can have a chat key and not require mousing.

this kind of thing is also generally useful for keyboard (or controller) accessibility, which seems a bit impossible at the moment.

also, is the only way to have a working multi-line text widget to draw the text myself?

![2017-01-13_11-05-52](https://cloud.githubusercontent.com/assets/219510/21942023/3a9a8b3a-d980-11e6-9d5c-d1c1a3fbe764.png)

**Comment by keharriso** [comment]
v2.2 lets you manually focus edit widgets. Unfortunately, I don't know of a way to create a chatbox -- you might want to post an issue to the [Nuklear](https://github.com/vurtun/nuklear) repository. Here is an example where enter focuses the edit box and commits the text if it's already focused:

```lua
local nuklear = require 'nuklear'

local ui

function love.load()
	ui = nuklear.newUI()
end

local active = false
local focus = false
local edit = {value = ''}
local messages = {}

function love.update(dt)
	ui:frameBegin()
	if ui:windowBegin('Focus Edit', 100, 100, 200, 100,
                          'border', 'title', 'movable') then
		ui:layoutRow('dynamic', 30, 1)
		if focus then
			ui:editFocus()
		end
		local state, changed = ui:edit('field', edit)
		active = state == 'active'
	end
	ui:windowEnd()
	ui:frameEnd()
	focus = false
end

function love.draw()
	ui:draw()
end

function love.keypressed(key, scancode, isrepeat)
	if key == 'return' then
		if active then
			table.insert(messages, edit.value)
			edit.value = ''
		else
			focus = true
		end
	end
	ui:keypressed(key, scancode, isrepeat)
end

function love.keyreleased(key, scancode)
	ui:keyreleased(key, scancode)
end

function love.mousepressed(x, y, button, istouch)
	ui:mousepressed(x, y, button, istouch)
end

function love.mousereleased(x, y, button, istouch)
	ui:mousereleased(x, y, button, istouch)
end

function love.mousemoved(x, y, dx, dy, istouch)
	ui:mousemoved(x, y, dx, dy, istouch)
end

function love.textinput(text)
	ui:textinput(text)
end

function love.wheelmoved(x, y)
	ui:wheelmoved(x, y)
end
```

**Comment by keharriso** [comment]
I am actually interested in this problem, so I went ahead and made an issue myself: https://github.com/vurtun/nuklear/issues/781
