### ISSUE TITLE
Sliders stuck

### ISSUE THREAD

**Issue by francmarx** [keharriso/love-nuklear#15]
Hello,
please change line 67 of overview.lua from
   nk.slider(0, slider, 1, 0.05)
to
   nk.slider(1, slider, 8, 1)
and try moving the slider.... sometimes it works, sometimes not !?!?!

Franc

**Comment by vurtun** [comment]
Sorry for taking this @keharriso, I am the author of nuklear and this is not so much a bug in love-nuklear but nuklear itself. I saw the issue and hopefully fixed the wrong slider behavior in commit vurtun/nuklear@8892727361b89c55da7dcabd46bb4b78eceeea39.
