### ISSUE TITLE
Indiviual Button styles

### ISSUE THREAD

**Issue by JanWerder** [keharriso/love-nuklear#17]
It would be great if the developer could optionally use individual styles for different buttons. Nuklear itself allows pushing a style in the 'style' property of the context struct (As seen in https://github.com/vurtun/nuklear/blob/master/demo/overview.c#L867 i.e.). 

From would I can judge, it looks like it would be a addition to the nk_love_button method (https://github.com/keharriso/love-nuklear/blob/master/src/nuklear_love.c#L1934), where the developer could push in the style and the method sets it to the &context if the parameter is supplied. 

Another approach could be a new method that sets the style for the command, in a push and pop style, which could be used in conjuction with the already available nk.stylePush command in love-nuklear

**Comment by JanWerder** [comment]
So I was able to replicate my use case with the use of the stylePush and stylePop commands.

```
if condition then
        nk.stylePush(self.myStyle)
      else
        nk.stylePush({})
      end
      activated = nk.button("Test")
      nk.stylePop()
```

I still think that a name based styling would be nicer and lead to cleaner code, but this works for now. So for anyone, who needs such a functionality, see the example above.

**Comment by keharriso** [comment]
I don't think I'm understanding you completely. What sort of code do you think should work? Maybe just a brief example.
