### ISSUE TITLE
More build instructions

### ISSUE THREAD

**Issue by JanWerder** [keharriso/love-nuklear#18]
This is not a real issue, but more of an enhancement.
It would be great if the repo would provide a more detailed instruction to building love-nuklear. I at least couldn't reproduce the builds with the steps provided. But of course this is not a love-nuklear issue, more so one of the developer, but it would be nice to have it either way.

**Comment by JanWerder** [comment]
Just to write it down what I got this far:

0. Clone the love-nuklear repo
1. Install TDM-GCC-64 (used in this guide) or MinGW
2. Download and Install the Visual Studio C++ Build Tools
3. Download LuaJit 2.0.4 as well 
4. Open the "Visual C++ 2015 x64 Native Build Tools Command Prompt" (may vary) and cd into your LuaJIT folder
5. Run the msvcbuild.bat, which should build LuaJIT
6. Modify the CMakeLists.txt (should be doabl with env vars as well, but didn't work in my case). Add the following lines at the top:
```
SET(CMAKE_C_COMPILER "C:/TDM-GCC-64/bin/gcc.exe")
SET(LUA_LIBRARIES "C:/Users/janwe/dev/luajit-2.0/src/lua51.dll")
SET(LUA_INCLUDE_DIR "C:/Users/janwe/dev/luajit-2.0/src")
```

This may vary depending on your paths.

After that open the cmd.exe

1. Run `cmake .` when you are in the path

Expected result:
```
-- Building for: NMake Makefiles
-- The C compiler identification is GNU 5.1.0
-- Check for working C compiler: C:/TDM-GCC-64/bin/gcc.exe
-- Check for working C compiler: C:/TDM-GCC-64/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found LuaJIT: C:/Users/janwe/dev/luajit-2.0/src/lua51.lib (found version "2.0.4")
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/janwe/dev/love-nuklear
```

2. Run `cmake --build . --config Release` while still being in the same path

Expected result:
```
[ 50%] Linking C shared module nuklear.dll
[100%] Built target nuklear
```

This spits out a nuklear.dll in the nuklear folder, which you can copy into your path or your Löve folder, which works on your Windows Platform.

**Comment by JanWerder** [comment]
So I got this to work and I would like to leave it here for the future. I updated my original comment

**Comment by keharriso** [comment]
I hope the current build instructions are to your satisfaction.
