### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by buckle2000** [keharriso/love-nuklear#2]
Either released binaries or the one I built with LuaJIT 2.0.4 locally does not work with love2d or luajit.

There is a error message:

> Error: error loading module 'nuklear' from file '.\nuklear.dll': 
> 找不到指定的程序。 (Cannot find given executable)

**Comment by JanWerder** [comment]
It seems like you don't have the dll in the right location. Where did you put it?

**Comment by buckle2000** [comment]
Right in the `example` folder.

**Comment by JanWerder** [comment]
To my knowledge you have to put in the folder of your love.exe

**Comment by buckle2000** [comment]
That did the trick. Thank you!
Have to check `package.cpath` first.
