### ISSUE TITLE
Does not support new Love2d 11.0 color values

### ISSUE THREAD

**Issue by micheal-earl** [keharriso/love-nuklear#25]
Color values in the most recent version of Love2d have been changed from 0-255 to 0.0-1.0 and are now percentage based. This results in everything that is drawn to the screen being white because any value over 1 is basically 255 now.

**Comment by zetef** [comment]
i really do not understand the reasoning behind this change from love2d.

**Comment by micheal-earl** [comment]
Yeah it was definitely unneeded. It just breaks so many libraries and projects. Really just a chore to port everything over to the new color values.

**Comment by zetef** [comment]
I think this change is made just because of damn shaders 🤷

**Comment by keharriso** [comment]
Fixed in #26 , thanks @jamestn529 .
