### ISSUE TITLE
White squares instead of UI elements when using LÖVE 11.1

### ISSUE THREAD

**Issue by olivier-grech** [keharriso/love-nuklear#27]
I tried running the example provided in both LÖVE **10.2** and **11.1**

This is the result (as expected) when using **10.2**:

![love102](https://user-images.githubusercontent.com/12234562/41428399-4b75dffa-700a-11e8-8520-9936c540d1dd.png)

This is the result when using **11.1**:

![love111](https://user-images.githubusercontent.com/12234562/41428426-5f874ff6-700a-11e8-9545-677204fd7a72.png)

**Comment by Muscipular** [comment]
build dll from master branch can resolve this problem

**Comment by sundowns** [comment]
I'm having trouble compiling from master, is it possible to have up-to-date binaries hosted? The latest release's binaries are not compatible with the latest version of LOVE as demonstrated in this issue.

**Comment by keharriso** [comment]
The color changes have been bundled into release v1.3, thanks for the issue.
