### ISSUE TITLE
Updated binaries?

### ISSUE THREAD

**Issue by sundowns** [keharriso/love-nuklear#28]
The most recently released binaries are not compatible with LOVE 11.1. They result in [this issue](https://github.com/keharriso/love-nuklear/issues/27) but supposedly this has been fixed in master. 

Currently I am unable to build from source and so this is unusable in LOVE 11.1. The [last release](https://github.com/keharriso/love-nuklear/compare/v1.2...master) was in December 2016. Is there any chance of a new release with updated binaries? 

Working with windows 64bit for reference, but it's probably nice to have up to date binaries across the board.

**Comment by keharriso** [comment]
I apologize, I'm on vacation at the moment, but I should have new binaries up by next week. Thanks for the issue.

**Comment by turbo** [comment]
I'd also appreciate more instructions on building with CMAKE. What actual path are required?

Edit: Needed `sudo apt install libluajit-5.1-2 libluajit-5.1-dev` on 16.04 :)

**Comment by keharriso** [comment]
I added more detailed build instructions. If it's still unclear, feel free to open a new issue.
