### ISSUE TITLE
Abnormal Value(Brightness) in color picker

### ISSUE THREAD

**Issue by buckle2000** [keharriso/love-nuklear#3]
![default](https://cloud.githubusercontent.com/assets/10850402/20674773/174148f6-b5c5-11e6-8753-a78d2aa5a7cb.PNG)
This looks darker than what I see the screenshots of *original nuklear*.

Other widgets have correct shading.

**Comment by keharriso** [comment]
Thanks for the issue! Should be fixed with  c676186.
