### ISSUE TITLE
Error when pushing style: 'attempt to index a nil value'

### ISSUE THREAD

**Issue by megagrump** [keharriso/love-nuklear#35]
Code to reproduce the issue:
```local nk = require('nuklear')
local ui = nk.newUI()

ui:stylePush({
	checkbox = {
		normal = love.graphics.newImage('checkbox.png'),
	},
})
```

Stack trace:
```
Error: attempt to index a nil value
stack traceback:
	[string "boot.lua"]:637: in function <[string "boot.lua"]:633>
	[C]: in function 'stylePush'
	main.lua:4: in main chunk
	[C]: in function 'require'
	[string "boot.lua"]:475: in function <[string "boot.lua"]:311>
	[C]: in function 'xpcall'
	[string "boot.lua"]:645: in function <[string "boot.lua"]:639>
	[C]: in function 'xpcall'
```

The error gets thrown when calling pushStyle() before calling frameBegin(). I have an app that pushes a style when it starts, before the first frameBegin() - this worked fine with an older version of love-nuklear.

Is this by design? Are static styles to be pushed in every frame?

**Comment by megagrump** [comment]
A workaround:
```
function love.load()
    ui:frameBegin()
    ui:stylePush(style)
    ui:frameEnd()
end
```

It's not pretty, but the style sticks between frames.

**Comment by keharriso** [comment]
v2.5 should solve this problem. Let me know if the issue persists.

**Comment by megagrump** [comment]
Works fine now, thanks
