### ISSUE TITLE
Moving windows feels sluggish

### ISSUE THREAD

**Issue by karai17** [keharriso/love-nuklear#4]
I'm checking out this awesome library and I noticed that it feels quite sluggish when I create a simple window and drag it around. Not sure if it's designed to be that way or not, but the window drags significantly behind my cursor.

My hardware should not be to blame, I am running a 6700K and a GTX 1070. I am using the precompiled Linux x86_64 module.

**Comment by keharriso** [comment]
Thank you for the report. Unfortunately, I haven't been able to replicate your issue. Does it apply to the provided "example/" program, and does it apply to the "nuklear/demo/x11_opengl3/" program? If those are unaffected, could you upload the .love file that is causing issues?

**Comment by karai17** [comment]
I am using the example program written in your README, verbatim. The x11_opengl3 demo seems to have the same issue. I'll post a video in a few moments. I apologize in advance if there is any flickering, I've been having trouble with recording video with OBS recently.

**Comment by karai17** [comment]
https://youtu.be/pOtH4pd3E-k

**Comment by keharriso** [comment]
I see what you're saying - I get the same effect. Seeing as the problem exists in the x11_opengl3 demo, the solution seems like it would have to be changing Nuklear itself. Maybe you'd get more mileage out of opening an issue there?

**Comment by karai17** [comment]
Yeah, this is clearly a nuklear issue and not with your binding. Thanks, I'll poke them about it!

**Comment by karai17** [comment]
https://github.com/vurtun/nuklear/issues/297

Response makes sense.
