### ISSUE TITLE
Direct number passed to property doesn't update

### ISSUE THREAD

**Issue by MangelMaxime** [keharriso/love-nuklear#46]
Hello,

when passing directly a number to `ui:property` the value can't get updated from the UI component.

However, if I pass it by wrapping it in a table (like in `edit2`) then it works.

```lua
local edit1 = 2
local edit2 = { value = 2 }

function Player:updateUI(ui) 
  if ui:windowBegin('Player infos', 100, 100, 200, 160,
			'border', 'title', 'movable', 'minimizable') then
		ui:layoutRow('dynamic', 30, 2)
		ui:label('Edit #1')
    ui:property("", 0, edit1, 3, 1, 1)
		ui:layoutRow('dynamic', 30, 2)
		ui:label('Edit #2')
    ui:property("", 0, edit2, 3, 1, 1)
	end
	ui:windowEnd()
end
```

![love-nuklear-property-bug](https://user-images.githubusercontent.com/4760796/73190274-0b28b000-4126-11ea-942c-a5a291dcb363.gif)

Am I doing something wrong?

**Comment by keharriso** [comment]
Line 8: You pass `edit1` to `ui:property`, but don't retrieve its return value (the updated property value). Change this:

```lua
ui:property("", 0, edit1, 3, 1, 1)
```

To this:



```lua
edit1 = ui:property("", 0, edit1, 3, 1, 1)
```

**Comment by MangelMaxime** [comment]
Oh ok, is this behaviour always the same?

I mean if I pass a table it will get updated directly, otherwise I have to store the result ?

Thank you for the quick answer :)

**Comment by keharriso** [comment]
Yes, this behavior is common among all widgets that take values. If you pass a table to `ui:slider` for example, the table's `value` field will be updated. If you pass a number, `ui:slider` will return the new number. Hope that helps.
