### ISSUE TITLE
nuklear.h CMake Build Error

### ISSUE THREAD

**Issue by Yeahyay** [keharriso/love-nuklear#47]
Following the build instructions on linux, using cmake gives the error. I've tried versions 2.5-2.6 and each version had the same issue.
```
CMake Error at CMakeLists.txt:9 (ADD_LIBRARY):
  Cannot find source file:

    src/nuklear/nuklear.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:9 (ADD_LIBRARY):
```

**Comment by keharriso** [comment]
Ensure you're cloning using the `--recursive` flag. That should hopefully solve your problem.

**Comment by Yeahyay** [comment]
Alright cloning with git --recursive worked. It didn't work initially because I grabbed the .tar.gz archives off of the releases page. Those archives had an empty src/nuklear folder so cmake was complaining. Same with the zips. Maybe you should fix it or specify to clone the repo recursively. But thanks for the help.
