### ISSUE TITLE
Error: error loading module 'nuklear-32' from file '.\nuklear-32.dll': %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by nothjarnan** [keharriso/love-nuklear#54]
Using 32-bit love2d 11.3.0 and 32-bit dll (renamed to nuklear-32.dll to make it clear its 32-bit)

Error: error loading module 'nuklear-32' from file '.\nuklear-32.dll':
        %1 is not a valid Win32 application.

stack traceback:
        [string "boot.lua"]:777: in function <[string "boot.lua"]:773>
        [C]: at 0x6cc8a030
        [C]: in function 'require'
        main.lua:43: in main chunk
        [C]: in function 'require'
        [string "boot.lua"]:570: in function <[string "boot.lua"]:380>
        [C]: in function 'xpcall'
        [string "boot.lua"]:787: in function <[string "boot.lua"]:780>
        [C]: in function 'xpcall'

**Comment by MikuAuahDark** [comment]
Are you sure the nuklear DLL is really 32-bit?

**Comment by keharriso** [comment]
Oddly, I get this error when I try to open the 32-bit dll with a 64-bit LOVE. Ensure that:
1. You don't rename the file. It needs to be `nuklear.dll`.
2. You've downloaded the 32-bit version (I assume this is true).
3. You're using the 32-bit version of LOVE (I think you might not be doing this).

Let me know more if your problem still isn't solved after these steps.
