### ISSUE TITLE
Cannot set button text background.

### ISSUE THREAD

**Issue by xiejiangzhi** [keharriso/love-nuklear#55]
Normal
![image](https://user-images.githubusercontent.com/1396853/86225026-3ffccf80-bbbc-11ea-9803-757be487b0d1.png)

Hover
![image](https://user-images.githubusercontent.com/1396853/86225046-4ab76480-bbbc-11ea-9f30-48088709d7c7.png)

```
ui:stylePush({
        button = {
          normal = '#99999944',
          hover = '#99999900',
          ['text background'] = '#ffffff00'
        }
      })
			if ui:button('Button') then
				print('button pressed!')
			end
      ui:stylePop()
```

It's seems that the text background is the same as normal or hover.

**Comment by keharriso** [comment]
I'll look into this, but one thing you can do to speed up the process is create a version of your test in C. Ideally, the C version would work as expected, meaning the problem is with LOVE-Nuklear and not Nuklear itself. You can find C tests in nuklaer/demo.

**Comment by xiejiangzhi** [comment]
![image](https://user-images.githubusercontent.com/1396853/86310440-adf2d680-bc50-11ea-8051-8f0fae18685d.png)
![image](https://user-images.githubusercontent.com/1396853/86310467-bc40f280-bc50-11ea-8c4c-5ec81ebbfbc6.png)

![image](https://user-images.githubusercontent.com/1396853/86310506-dbd81b00-bc50-11ea-81cf-758b95ae6e6d.png)

In C version, it has no text background and cannot change the text background.

**Comment by keharriso** [comment]
OK, so if I understand correctly, the C version lists text_background as a button style property, but the property doesn't actually do anything. This would explain why it doesn't work in LOVE-Nuklear. In this case, you might want to start an issue with the [upstream repository](https://github.com/Immediate-Mode-UI/Nuklear). If I misunderstood you, please let me know. Thanks for the issue.

**Comment by xiejiangzhi** [comment]
I just copied the C version description and created a new issue https://github.com/Immediate-Mode-UI/Nuklear/issues/158

**Comment by xiejiangzhi** [comment]
So, I think we should fix the problem of love version. Button should remove the text background.
