### ISSUE TITLE
Question : install in windows10 mingw64

### ISSUE THREAD

**Issue by deb75** [keharriso/love-nuklear#57]
Hello,

I would like to use `love-nuklear` for a project on windows 10. I have mingw64 installed.

`love` is available for windows and you provide a binary for windows 64bit. What do I need else to make it work ?
Do I need to install `luajit` ?

**Comment by keharriso** [comment]
Hello deb75,

The windows binaries are built using the MSVC compiler. All that you should need to do is place nuklear.dll in the same folder as your Lua code and import it using `local nuklear = require 'nuklear'`. Let me know if you either get it working or have some trouble. You should not need to install `luajit`.

Thanks,
keharriso
