### ISSUE TITLE
Setting the normal value in the property skin, breaks the skin

### ISSUE THREAD

**Issue by JanWerder** [keharriso/love-nuklear#6]
So this works: 

  	['property'] = {     
  		['label normal'] = '#241414',
  		['label hover'] = '#241414',
  		['label active'] = '#241414',
  	},

and this does not:

	['property'] = {     
		['normal'] = '#241414',   
		['label normal'] = '#241414',
		['label hover'] = '#241414',
		['label active'] = '#241414',
	},

The result is a half broken skin, with some f the default values set and others taken from the skin

**Comment by keharriso** [comment]
Does this do what you were expecting?
```lua
['property'] = {
	['normal'] = '#241414',
	['label normal'] = '#241414',
	['label hover'] = '#241414',
	['label active'] = '#241414',
	['edit'] = {
		['normal'] = '#241414'
	},
	['inc button'] = {
		['normal'] = '#241414'
	},
	['dec button'] = {
		['normal'] = '#241414'
	}
}
```

**Comment by JanWerder** [comment]
Well this doesn't work either. it seems okay, if I don't set the normal value

**Comment by keharriso** [comment]
I'm not sure what you're seeing or expecting. Could you upload some screenshots of the problem - one with `normal` and one without? A .love file would be useful, too.

**Comment by JanWerder** [comment]
Without:
![love_2016-12-15_17-04-45](https://cloud.githubusercontent.com/assets/596986/21231443/a051ab74-c2e8-11e6-8bec-6bba6eb8e398.png)

With:
![love_2016-12-15_17-04-29](https://cloud.githubusercontent.com/assets/596986/21231459/a5d70580-c2e8-11e6-8701-4e1b4a8a1143.png)

My Löve fileas a zip if you want to try it yourself.
http://uploaded.net/file/r36jiihx

**Comment by keharriso** [comment]
Thanks for the catch, I believe the issue should be solved with the latest commit. Here are some tentative binaries for you to test. Let me know whether or not they fix the problem.
[love-nuklear-1.1.3-linux32.zip](https://github.com/keharriso/love-nuklear/files/655454/love-nuklear-1.1.3-linux32.zip)
[love-nuklear-1.1.3-linux64.zip](https://github.com/keharriso/love-nuklear/files/655452/love-nuklear-1.1.3-linux64.zip)
[love-nuklear-1.1.3-win32.zip](https://github.com/keharriso/love-nuklear/files/655453/love-nuklear-1.1.3-win32.zip)
[love-nuklear-1.1.3-win64.zip](https://github.com/keharriso/love-nuklear/files/655455/love-nuklear-1.1.3-win64.zip)

**Comment by JanWerder** [comment]
That fixes it 👍
