### ISSUE TITLE
love transforms don't work properly

### ISSUE THREAD

**Issue by karai17** [keharriso/love-nuklear#9]
When using `love.graphics.[translate/rotate/scale]`, bad things happen. Strange mask clipping, input isn't properly transformed, etc. The use case I am trying to implement is the ability to pan the whole UI around, or zoom in and out.

**Comment by keharriso** [comment]
Unfortunately, I'm not sure how to make Nuklear behave with the `love.graphics` transformations. There is no way to get LOVE's current transformation, so it's impossible to apply it to the UI.

The simplest solution would be to add separate `nk.[translate/rotate/scale]` functions, but even that has problems. Internally, Nuklear generates draw commands, many of which contain axis-aligned rectangles. There is no support for rotated rectangles, so `nk.rotate` would be difficult to implement. I think if I switch LOVE-Nuklear to render to an internal canvas, it would be possible, but would mean that there can only be one transformation that applies to the entire UI at once (which I don't think is really that big of a problem).

**Comment by karai17** [comment]
I think a single set of transforms for the whole UI makes sense considering nk.draw is a single function. It would be difficult to apply several different transforms to that unless you were thinking of applying transforms in update when creating the UI elements.

However this brings up a question. Is it possible to them have two UI instances? One for static elements and one for transformable elements? Or if they as simple as 

```
local nk = require "nuklear"
local mk = require "nuklear"
```

?

**Comment by karai17** [comment]
Perhaps nk.init should create an instance? 

`local static_ui = nk.init()`

**Comment by keharriso** [comment]
> Perhaps nk.init should create an instance?
>
> `local static_ui = nk.init()`

Thanks for the suggestion, that makes a lot of sense. I'll try to have that done for v2.0, ideally alongside the transformation functions (no promises on a timeline).

**Comment by karai17** [comment]
awesome, I look forward to it!

**Comment by keharriso** [comment]
Attached are the beta binaries for v2.0. You can create multiple contexts and apply transformations to each of them. You can see the updated example [here](https://github.com/keharriso/love-nuklear/tree/release-2.0/example). If you have any problems, let me know. Once any kinks are worked out, I'll make a proper release and update the documentation.
[love-nuklear-2.0b1-linux32.zip](https://github.com/keharriso/love-nuklear/files/678263/love-nuklear-2.0b1-linux32.zip)
[love-nuklear-2.0b1-linux64.zip](https://github.com/keharriso/love-nuklear/files/678265/love-nuklear-2.0b1-linux64.zip)
[love-nuklear-2.0b1-win32.zip](https://github.com/keharriso/love-nuklear/files/678266/love-nuklear-2.0b1-win32.zip)
[love-nuklear-2.0b1-win64.zip](https://github.com/keharriso/love-nuklear/files/678264/love-nuklear-2.0b1-win64.zip)

**Comment by karai17** [comment]
These seem to be working mostly fine. We're having an issue where the coordinates are not transformed when polling them, so for instance having non-nuklear elements attack to the nuklear elements doesn't work.

**Comment by keharriso** [comment]
Thanks for continuing to share. Is it possible to isolate the problem as a .love file I can use to fix it?

**Comment by karai17** [comment]
https://my.mixtape.moe/bbvsbo.love

In this example, I am printing out the values of the window's position. For some reason, X is coming up as nan and Y is 4 pixels off... But more notably, when you click and drag the graph around, you will note that the X and Y positions being reported do not change. This affects rotate and scale, too.

**Comment by keharriso** [comment]
If the problems still exist with the latest version, let me know and post an example.

**Comment by keharriso** [comment]
Part of the problem is you want to use `ui:windowGetPosition()` instead of `ui:widgetPosition()` (the latter adds padding pixels). About the positions not changing: if you want to do local graphics calls you should use `love.graphics.translate(...)` with the same arguments you give to `ui:translate`. Same for rotate and scale. Hopefully that helps.
